#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := rpm_tuning_off_load_direct_pid_one_wheel

include $(IDF_PATH)/make/project.mk
