#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := rpm_using_frequency_measurement

include $(IDF_PATH)/make/project.mk
