#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := rpm_tuning_direct_pid_two_wheel

include $(IDF_PATH)/make/project.mk
